package org.example

object Database {
    val items = listOf(
        "Kotlin",
        "Kotlin Multiplatform",
        "Kotlin Coroutines",
        "Kotlinx Serialization",
        "Java",
        "JavaScript",
        "Jetpack Compose",
        "Jetpack Navigation",
        "Gradle",
        "Groovy",
        "Go",
        "Rust",
        "Ruby",
        "Retrofit",
        "Room",
        "Python",
        "PyTorch",
        "Swift",
        "SwiftUI",
        "Scala",
        "Spring Boot",
        "SQLite",
        "TypeScript",
        "Terraform",
        "Docker",
        "Dagger",
        "Django",
        "Flutter",
        "Flow",
        "Firebase",
        "C",
        "C++",
        "C#",
        "Clojure",
        "Elixir",
        "Erlang",
        "Haskell",
        "Node.js",
        "Next.js",
        "Nginx"
    )
}